name: CI Test

on: [push, pull_request]

# Cancel prev CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  VERSION: ${{ github.event.pull_request.number }}

permissions:
  contents: read
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install deps
        run: yarn install

      - name: Typecheck
        run: yarn typecheck

      - name: Template react-recoil Code Check
        run: |
          cd templates/template-react-recoil
          yarn install
          yarn prettier --check .
          yarn lint --no-cache
          yarn tsc
      
      - name: Template react-ts Code Check
        run: |
          cd templates/template-react-ts
          yarn install
          yarn prettier --check .
          yarn lint --no-cache
          yarn tsc

  ############################ Coverage ###########################
  coverage:
    name: test-coverage
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: actions/download-artifact@v3
        with:
          name: coverage-artifacts
          path: persist-coverage

      - name: Merge Code Coverage
        run: |
          npx nyc merge persist-coverage/ coverage/coverage-final.json
          npx nyc report --reporter text -t coverage --report-dir coverage
          rm -rf persist-coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          # use own token to upload coverage reports
          token: ${{ secrets.CODECOV_TOKEN }}
