# Compile, bundle, and upload application bundles
# to a cloud storage on each pull request to "main".
# https://help.github.com/actions

name: CI

on:
  workflow_dispatch: {}

env:
  CI: true
  VERSION: ${{ github.event.pull_request.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: [14, 16, 18]

      - name: Install deps
        run: yarn install

      - name: Typecheck
        run: yarn typecheck

      - name: Code Check
        run: |
          cd template-react-vite-recoil
          yarn install
          yarn prettier --check .
          yarn lint --no-cache
          yarn tsc
