name: Release

on:
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine Release version
        id: get_version
        run: echo ::set-output name=release_version::$(cat package.json | jq -r '.version')

      - name: Perform Github Release
        uses: softprops/action-gh-release@v1
        env:
          FILE_PATTERN: "!(.github)"
        with:
          name: v${{ steps.get_version.outputs.release_version }}
          tag_name: v${{ env.get_version.outputs.release_version }}
          generate_release_notes: true
